### PR TITLE
fix: delete the dead link in the Github status payload

### LINKED ISSUE #126: GitHub status payload has invalid url
When a status is set on the commit, a URL is provided with it. However this URL appears to be broken:

```
{
  "id": 4312453694,
  "sha": "11426f2c689a6a7ccb78a6c6e366ce040e5f797d",
  "name": "j2sol/demobrigade",
  "target_url": "http://169.48.217.138:32586/log/j2sol/demobrigade/id/11426f2c689a6a7ccb78a6c6e366ce040e5f797d",
  "context": "brigade",
  "description": "Brigade build passed",
  "state": "success",
```

That IP and port is indeed the exposed service for the Brigade gateway service, but that URL results in a 404.

### PR DESCRIPTION
**Pull request by meyerbaptiste**
This PR fixes #126.

### CODE REVIEW

**Comment by dunglas** [comment]
It was convenient to have a webpage with the logs. Is it intended to remove it?

**Comment by technosophos** [comment]
The new version will be out by the end of this week (just in time for KubeCon)

**Comment by technosophos** [comment]
Gonna confirm with @adamreese that we can merge this. Then I will.

**Comment by adamreese** [comment]
I am fine deleting this until we can fix properly

**Comment by technosophos** [comment]
Okay, we can now set status from inside of a brigade.js like this: https://github.com/technosophos/github-notify

**Pull request merged**
