### PR TITLE
fix(docs): add correct key for commit sha value

### LINKED ISSUE #471: Document for GitHub integration with brigade seems to be outdated
Hi All,
I tried exploring brigade, and was following the tutorial for setting up the integration with github:
https://azure.github.io/brigade/intro/tutorial04.html
But was getting "undefined" with "e.commit", I tried a lot of things but seemed to be working, so I checked on your slack community and someone suggested to replace "e.commit" with "e.revision.commit".

This worked and its running fine now. Thanks a lot. But I request you to please update your docs so that no one else faces the same issue.

### PR DESCRIPTION
**Pull request by OrthoDex**
Fixes #471

### CODE REVIEW

**Comment by OrthoDex** [comment]
Hi @technosophos! Is there anything else that would be required in this PR?

**Comment by radu-matei** [comment]
Hey, @OrthoDex!
First of all, thanks for your contribution!

Going over all other references for the event commit, I came across the following:

- the document referring to the `BrigadeEvent` class - https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-brigadeevent-class - as we can see in the `BrigadeEvent` TypeScript class, it does not contain the `commit` property anymore, but instead expses it through a `revision` property - the doc should reflect that.

- a portion of documentation referring to an `Event` object - https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-event-object
@technosophos - is the `Event` object mentioned in the docs still used?

**Comment by technosophos** [comment]
@radu-matei yeah, the Event object is still used in a few places, though it might be constructed as a bare object in most cases.

**Comment by OrthoDex** [comment]
@radu-matei Thanks for the feedback! I'll update those references in the PR as well.

**Comment by OrthoDex** [comment]
Hey @radu-matei, anything else to be added to this PR?

**Comment by vdice** [comment]
Sorry for the delay and thank you again for these changes @OrthoDex ; merging this in!

**Pull request merged**
