### PR TITLE
Add a theme for Docs

### PR DESCRIPTION
**Pull request by flynnduism**
This draft adds a Hugo site + Netlify config in order to generate a static site for the Brigade Docs.

Currently, we use the basic Github Pages (Jekyll) theme for the docs but it lacks any navigation or indexing, so it's difficult to browse. [https://azure.github.io/brigade/](https://azure.github.io/brigade/)

---

Having a Hugo version would mean the ability to add better menus, layout and fully customize the docs UX. Here's a preview of the work in progress: [https://brigade-docs.netlify.com/](https://brigade-docs.netlify.com/)

---

### To Dos:

- [x] fix subpages and links to them
  - [x] index content for /intro
  - [x] index content for /topics 
- [x] improve the theme styling
- [x] create a detailed menu of contents
- [x] mobile fixes
- [x] update favicon
- [x] tidy up the assets so these additions add as little noise to the brigade project as possible
  - [x] minify dependancies
  - [x] move as much as possible from root into /docs
  - [x] use Hugo Pipelines (via makefile) rather than gulp for scss

### CODE REVIEW

**Comment by flynnduism** [comment]
Pointed [docs.brigade.sh](https://docs.brigade.sh/) at the netlify site. Working on fixing up the theme and broken links now.

**Comment by flynnduism** [comment]
Theme added to [docs.brigade.sh](https://docs.brigade.sh) and Brigade-ified.

brig-docs

**Comment by dgkanatsios** [comment]
It looks awesome!

**Comment by radu-matei** [comment]
This looks great!

One small issue right now is that the images are not loading correctly -- possibly because before, they were rendered directly and in most articles they are inserted using and `img` tag, with the filepath relative to the markdown. See [the ingress doc for example](https://docs.brigade.sh/topics/ingress/).

But this looks fantastic!

**Comment by flynnduism** [comment]
Good call @radu-matei - I can affix the sidebar contents to the viewport for better a scroll/browsing UX.

Regarding table of contents, do you mean like a summary of the current page TOC, for skipping up and down the current view?

Currently the left hand menu auto generates based on the markdown files present in `docs/content/`. Having a three column layout is a bit busier, not ideal for a small / medium screen IMO but could add a section that appears for large display. Will create a follow up issue from this PR to layout ideas.

**Comment by radu-matei** [comment]
Yeah, another PR seems like a great idea, this PR should not be blocked by that.

Thanks!

**Comment by flynnduism** [comment]
> Good call @radu-matei - I can affix the sidebar contents to the viewport for better a scroll/browsing UX.

Added this:

sidebar

**Comment by dgkanatsios** [comment]
Should we also open a separate issue/PR to remove custom navigation?
capture

**Comment by flynnduism** [comment]
Yeah good idea @dgkanatsios

**Comment by flynnduism** [comment]
Added (and removed) a bunch of extra reviewers somehow - sorry for the spam. 

I'm gonna merge this in now that I got the final item (Hugo Pipelines) working and building ok on netlify. Will follow up with a PR to change the links in the readme and on the site to use the new `docs.brigade.sh` site.

**Pull request merged**
