### PR TITLE
Add 'closed' as allowed pull_request event

### PR DESCRIPTION
**Pull request by jdotjdot**
We're planning to use Brigade for Github automation in some ways as a replacement for Hubot.  One of the first events we plan to handle is when pull requests are closed or merged.  This PR adds `"closed"` as an allowed pull request event.

(Also updates `.gitignore`.)

### CODE REVIEW

**Comment by technosophos** [comment]
@jdotjdot This looks great. As soon as the CLA is signed, ping me and I will merge.

**Comment by jdotjdot** [comment]
Cool.  A lot more coming as well.  Is there a Slack channel you guys are on where I can ask a few questions?

I'm getting our legal department to review the CLA; I'll sign once it's approved.

**Comment by technosophos** [comment]
@jdotjdot we are in #brigade on the Kubernetes slack

**Comment by jdotjdot** [comment]
@technosophos CLA signed

**Comment by technosophos** [comment]
Uh-oh... now there's other stuff on here for a different issue. Can you do that as a separate PR and I'll get the original one merged?

**Comment by jdotjdot** [comment]
Whoops--will fix this.

**Pull request closed without merging**
